run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

linters-settings:
  gosec:
    excludes:
      - G404

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
