before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: darwin
        goarch: arm64
        goarm: "7"
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le
      - goos: freebsd
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: darwin
        goarch: s390x
      - goos: freebsd
        goarch: s390x
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
    binary: D5r
    hooks:
      post:
        - cmd: echo "Build completed for {{.Os}}/{{.Arch}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*
      - CHANGELOG*
      - docs/*
      - configs/*

nfpms:
  - maintainer: "D5r <22891046+wikczerski@users.noreply.github.com>"
    description: "D5r - Docker Container Management Tool"
    homepage: "https://github.com/wikczerski/D5r"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: "D5r"
        dst: /usr/local/bin/D5r
      - src: "README.md"
        dst: /usr/share/doc/d5r/README.md
      - src: "LICENSE"
        dst: /usr/share/doc/d5r/LICENSE



checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: wikczerski
    name: D5r
  draft: false
  prerelease: false
  name_template: 'v{{ .Version }}'
