colors:
  header: "#FFD700"     # Gold header
  border: "#87CEEB"     # Sky blue borders
  text: "#F0F8FF"       # Alice blue text
  background: "default" # System default background
  success: "#32CD32"    # Lime green success
  warning: "#FFA500"    # Orange warning
  error: "#DC143C"      # Crimson error
  info: "#4169E1"       # Royal blue info

shell:
  border: "#87CEEB"     # Sky blue borders (matching theme)
  title: "#FFD700"      # Gold title (matching header)
  text: "#F0F8FF"       # Alice blue text (matching theme)
  background: "default" # System default background (matching theme)
  cmd:
    label: "#32CD32"      # Lime green label (matching success)
    border: "#87CEEB"     # Sky blue border (matching theme)
    text: "#F0F8FF"       # Alice blue text (matching theme)
    background: "default" # System default background (matching theme)
    placeholder: "#B0C4DE" # Light steel blue placeholder

containerExec:
  label: "#FFD700"      # Gold label (matching header)
  border: "#87CEEB"     # Sky blue border (matching theme)
  text: "#F0F8FF"       # Alice blue text (matching theme)
  background: "#2F4F4F" # Dark slate gray background
  placeholder: "#B0C4DE" # Light steel blue placeholder (matching shell)
  title: "#FFD700"      # Gold title (matching header)

commandMode:
  label: "#FFD700"      # Gold label (matching header)
  border: "#87CEEB"     # Sky blue border (matching theme)
  text: "#F0F8FF"       # Alice blue text (matching theme)
  background: "#2F4F4F" # Dark slate gray background
  placeholder: "#B0C4DE" # Light steel blue placeholder (matching shell)
  title: "#FFD700"      # Gold title (matching header)
